from tools.chaos_pendulum.models import ColorTheme, PendulumPreset

THEMES: dict[str, ColorTheme] = {
    "cyber_aurora": ColorTheme(
        id="cyber_aurora",
        name="🌌 賽博極光 (Cyber Aurora)",
        description="霓虹電光藍與紫羅蘭漸層，極具未來感的流光軌跡",
        background="#0a0a14",
        glow_color="#00f0ff",
        trail_colors=["#00f0ff", "#7000ff", "#ff007b", "#00ffaa"],
    ),
    "solar_amber": ColorTheme(
        id="solar_amber",
        name="🍂 日光琥珀 (Solar Amber)",
        description="金黃琉璃與古銅暖金，散發恆星般的微暖光暈",
        background="#0f0c08",
        glow_color="#ffaa00",
        trail_colors=["#ffcc00", "#ff6600", "#ff3300", "#ffe680"],
    ),
    "monochrome_ink": ColorTheme(
        id="monochrome_ink",
        name="🖤 玄黑水墨 (Monochrome Ink)",
        description="如國畫狂草般的純白宣紙黑墨，極簡大氣",
        background="#050505",
        glow_color="#e0e0e0",
        trail_colors=["#ffffff", "#cccccc", "#888888", "#555555"],
    ),
    "abyssal_bio": ColorTheme(
        id="abyssal_bio",
        name="🌊 深海幽光 (Abyssal Bio)",
        description="萬米深淵生物螢光，清澈的青碧與幽暗海藍",
        background="#030d12",
        glow_color="#00ffcc",
        trail_colors=["#00ffcc", "#0088ff", "#00ff88", "#2ee6a8"],
    ),
    "doppler_prism": ColorTheme(
        id="doppler_prism",
        name="🌈 多普勒光譜 (Doppler Prism)",
        description="七彩色散全光譜，依照運動速度綻放絢麗彩芒",
        background="#08080c",
        glow_color="#ffffff",
        trail_colors=["#ff0055", "#ffaa00", "#00ff66", "#00ccff", "#aa00ff"],
    ),
}

PRESETS: list[PendulumPreset] = [
    PendulumPreset(
        id="classic_double",
        name="經典雙擺 (Double Pendulum)",
        num_links=2,
        speed=1.0,
        damping=0.0,
        swarm_count=1,
        trail_persistence=0.965,
        theme_id="cyber_aurora",
    ),
    PendulumPreset(
        id="triple_chaos",
        name="三階狂亂 (Triple Chaos)",
        num_links=3,
        speed=1.0,
        damping=0.0,
        swarm_count=1,
        trail_persistence=0.97,
        theme_id="solar_amber",
    ),
    PendulumPreset(
        id="butterfly_swarm",
        name="蝴蝶效應群集 (Butterfly Swarm 30x)",
        num_links=2,
        speed=1.2,
        damping=0.0,
        swarm_count=30,
        trail_persistence=0.95,
        theme_id="doppler_prism",
    ),
    PendulumPreset(
        id="cosmic_slow",
        name="深空慢舞 (Cosmic Slow Drift)",
        num_links=3,
        speed=0.5,
        damping=0.0,
        swarm_count=1,
        trail_persistence=0.985,
        theme_id="abyssal_bio",
    ),
    PendulumPreset(
        id="quad_whip",
        name="四節柔鞭 (Quadruple Whip)",
        num_links=4,
        speed=1.4,
        damping=0.0,
        swarm_count=1,
        trail_persistence=0.96,
        theme_id="monochrome_ink",
    ),
]
